### ISSUE TITLE
A user should be able to transfer a project to another user

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#230] opened 2020-12-03 23:42 UTC
## Story

As a user, I would like to transfer a project profile to another existing user so that they can manage it going forward.

## Description

Currently the person who requested a project is the only person who can see it in their dashboard. We recognize that this needs to work differently as some people may request it, but not oversee the project long term (think ppl on holidays etc). We need to implement the functionality so that users can transfer projects between them.

## Done When

A user can logon to the registry and transfer a project to another user who has logged at least one time with an existing database record. Then, the project should be visible on the new persons dashboard.

**Comment by yhfreeman** [comment] 2021-01-14 18:09
Hi @jleach, could you confirm this is the Duplicate of #91 thanks

**Closed** 2021-04-15 02:29 UTC
Labels: component/api, component/db, component/web, wontfix
