### ISSUE TITLE
Request has been stuck in "Pending Edit" state for weeks

### ISSUE THREAD

**Issue by victorchong** [bcgov/platform-services-registry#761] opened 2022-08-02 22:26 UTC
**Describe the issue**
Submitted to change a project's PO. Current status shows as "Pending Edit".

**Additional context**
Former PO is no longer with the Province.

**Definition of done**
Requested change has been completed and status changes to "Provisioned"

**Comment by ShovelHand** [comment] 2022-08-09 19:18
@mitovskaol Is there any more information to go with this? What project? Who is the former PO?

**Comment by mitovskaol** [comment] 2022-08-09 20:38
@ShovelHand A good first step would be to reach out to the person who submitted the issue and get more information from them.

**Comment by ty2k** [comment] 2022-08-11 20:31
@victorchong has confirmed by email that this request was able to be completed, and that the status in the Project Registry app shows "Provisioned" as expected:

![Project Registry screenshot](https://images.zenhubusercontent.com/5ec709daacce4878764898c4/bce81b2f-a7b7-45a3-bbaa-e162ba64f2d1)

In this case, the root cause was that a record already existed for the request in the internal `namespaces` GitHub repository. The callback that should have been sent to the Registry application was never received, so the Registry was unaware that the job was already completed. Billy was able to solve this by manually making a small change on the record in the `namespaces` repo via a pull request, then triggering a sync process on the Provisioner. GitHub noticed this difference and allowed the Provisioner to send its pull request, which, when merged, emitted a callback to the Registry.

**Closed by ty2k** 2022-08-11 20:31 UTC
Labels: bug, app-development
