### ISSUE TITLE
The API should accept updates for profile contacts

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#137] opened 2020-10-20 21:46 UTC
## Story
As a user, I would like to submit updates to the contact details of a given project.

## Details
Currently, profile contacts are generated during the project creation stage. As PO and TC may change over time, it is important to be able to adjust these fields as necessary

## Done When
The API is capable of accepting updates to profile contacts

**Comment by sbathgate** [comment] 2020-11-13 21:56
I think this is a duplicate of Issue #173 . I will close if that is the case.

**Closed** 2020-11-19 00:16 UTC
