### ISSUE TITLE
Increase the registry backup frequency to 1h

### ISSUE THREAD

**Issue by jleach** [bcgov/platform-services-registry#150] opened 2020-10-29 18:25 UTC
## User Story

As a SRE I would like to know that if my prod database gets corrupt I can restore from a recent backup.

## Description

Currently the backup runs once a day. It would be better if it ran hourly, keeping 24 of backups so that we never loose more than an hour of data if the database is ever deleted.

## Done When

Backups run hourly and 24 are retained for a day.

**Comment by yhfreeman** [comment] 2021-02-24 19:21
The ticket is carried from the previous sprint as the wrapping-up process becomes more time-consuming than previously expected.
The reasons are as follow:
- The backup container connection issue we had recently in dev namespace (a blocker to further testing).
- The nature of using backup-storage app to do hourly backup is experimental.
  - Copies to retain / prune in relation to ensuring storage is enough.
  - Given the end-users of registry portal, do we really hourly backup outside of working hours?
    This is where it's possible to convert this ticket into a spike^

**Comment by lukegonis** [comment] 2021-03-04 18:19
@mitovskaol there is more discovery required with this issue, it is not required to achieve the sprint goal, moving it to the backlog, let @yhfreeman if you want it to remain in the sprint.

**Comment by IanKWatts** [comment] 2021-04-09 23:12
There was an issue with the old version of 'backup-container' that was being used.  I have rebuilt it using the latest version and redeployed it in Dev.  I'll keep an eye on it and will likely adjust the retention settings.

**Comment by IanKWatts** [comment] 2021-04-10 05:12
Looks good so far.  I'll review the changes with the team on Monday and establish our backup retention rules.

**Comment by IanKWatts** [comment] 2021-04-12 16:30
@jleach  @yhfreeman Hourly DB backups are now enabled in the platform-registry-dev environment.  We'll want to make some adjustments, I imagine, but here's what we have right now:

- DB backups done on the hour from 8am to 5pm on weekdays
- DB backups done on Saturday and Sunday at 8am
- 30 daily backups retained (three days worth)
- 4 weekly
- 2 monthly
- The Dev backups are quite small, so it doesn't look like disk space will be an issue there.  Is the Production DB much larger?

Let me know what you think.

**Comment by yhfreeman** [comment] 2021-04-13 23:47
@IanKWatts Thanks for your work. Earlier today I happened to have updated the dev db to match prod db for other reasons. So in theory, if we run dev backup container for a long enough period that we can verify the intended backups and retentions work, it should give us some level of confidence in prod.

**Comment by IanKWatts** [comment] 2021-04-14 00:00
@yhfreeman Thanks for the update.  I can see that the DB backup file size is slightly larger starting at 1:00.  Disk space shouldn't be a problem.

One problem, however, is that the verification command is failing.  I've done some investigation into that, but it's still not working.  Would you be able to manually test a DB backup file?

**Comment by yhfreeman** [comment] 2021-04-14 00:59
@IanKWatts inside the backup container you can run something like
```
./backup.sh -r registry-patroni-master:5432/registry -f /backups/weekly/2021-04-11/registry-patroni-master-registry_2021-04-11_13-00-00.sql.gz
```

**Comment by IanKWatts** [comment] 2021-04-15 00:05
Thanks for the confirmation, @yhfreeman 

I've fixed the verification process, which had been erroring out.  The backup-container scripts expect the DB username to be different from the default 'postgres' admin user.  It is also expected that the username and password environment variables should be based on the DB hostname.  So, in the deployment's environment variables...

- DATABASE_USER is replaced with REGISTRY_PATRONI_MASTER_USER
- DATABASE_PASSWORD is replaced with REGISTRY_PATRONI_MASTER_PASSWORD
- The username is still taken from the secret 'registry-patrons-creds', but uses 'app-db-username' instead of 'superuser-username'
- Password is changed from 'superuser-password' to 'app-db-password'

Verification of the most recent backup, as specified in the crontab, just takes a few seconds to run.  It can be run manually on the backup container with:
`./backup.sh -v all` 

Last thing is to decide on how many of each type of backup to keep.  Looks like disk space will not be an issue.

**Comment by IanKWatts** [comment] 2021-04-19 16:52
@yhfreeman has implemented these changes in the Production environment and confirmed that the backups are working as desired.  Backups are currently taken every hour from 8am to 5pm on weekdays and once a day at 8am on weekends.  Retention is set to 60 for daily backups, 4 for weekly backups, and 2 for monthly backups.

If necessary, adjustments to the number of backups to retain can be set in the Deployment configuration for the backup container.  The backup schedule (cron) can be updated in the ConfigMap.

The Test environment does not have a DB backup container.

**Closed by IanKWatts** 2021-04-19 16:52 UTC
Labels: app-development, techdebt
