### ISSUE TITLE
Public Cloud eMOU Form - Admin approval process

### ISSUE THREAD

**Issue by Iryna-Kaplun** [bcgov/platform-services-registry#3500] opened 2024-08-08 20:14 UTC
Public Cloud eMOU Form
EA signing process
Admin approval process
PDF download
workflow diagram

**Comment by funtigr** [comment] 2024-08-28 22:41
@junminahn 
I found a couple of issues with Admin approval flow:
1. The Products that were added before implementing the feature need the Approval of Expense Authority before editing. Though it is supposed that the team already has MOU signed in different form, otherwise they would not be allowed to operate in Public Cloud.
<img width="1463" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUtXQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ab36d3a6e6cf1146834a2fdd8d7b5977cf07220/image.png" alt="image.png" />

2. A low priority corner case: if user uses the Billing Code that is used in Request that is not yet approved, he can just click the checkbox "I have received approval". The Admin would still need to approve both Requests. But if, for example, Admin first approves the Requests that do not need looking into new Expense Authority documents, then he can approve the Request that has non-checked Billing Code and Expense Authority person.

3. I faced it two times but can't reproduce: when I try to perform an action (sign eMOU or approve as a Billing Reviewer), I get an error: "You are not assigned to perform this task".

4. Maybe later we would edit this text about having MoU in place, because for now it will not be needed. Also it is shown to Reviewer, though text is written for the User:
<img width="1507" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL21XQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15bf52dafcf5394e897e80c49c8c2eb7883d669d/image.png" alt="image.png" />

**Comment by junminahn** [comment] 2024-08-29 17:10
@funtigr 
#1: they will need to sign the eMOU later; I will add the button the product edit page.
#2: I guess, we will need to prevent them using the billing code that has been signed & approved yet.
#4: let's delete the note.

**Comment by junminahn** [comment] 2024-08-29 17:37
@funtigr let's address #1 in another ticket as it require migration script.

**Comment by funtigr** [comment] 2024-08-30 00:16
Tickets:
For #1: https://app.zenhub.com/workspaces/app-dev-team-646fdb4400ed8c0021aceeb4/issues/gh/bcgov/platform-services-registry/3634
For #2: https://app.zenhub.com/workspaces/app-dev-team-646fdb4400ed8c0021aceeb4/issues/gh/bcgov/platform-services-registry/3643
For #4: https://app.zenhub.com/workspaces/app-dev-team-646fdb4400ed8c0021aceeb4/issues/gh/bcgov/platform-services-registry/3644

**Closed by funtigr** 2024-08-30 00:16 UTC
